version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app
      - ./backend/data/sqlite:/app/data/sqlite
      - ./backend/data/chromadb:/app/data/chromadb

    environment:
      - PYTHONUNBUFFERED=1

      # Tells Python it's running in development mode
      # change later on
      - ENVIRONMENT=development
      - SQLITE_DB_PATH=/app/data/sqlite/app.db
      - CHROMA_PERSIST_DIRECTORY=/app/data/chromadb

    restart: unless-stopped

    # check the health of the container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
